[package]
name = "fiv-term"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
fiv-log = { git = "https://github.com/fives-55555/fiv-log" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.0", features = [
  "Win32_System_Console",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_Security_Authorization",
] }

[features]
debug = []
ter_test = []
virt_keys = []
